# Generated by Django 5.2.5 on 2025-10-18 17:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(help_text='Max Characters 500', validators=[django.core.validators.MaxLengthValidator(500)])),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='category-images/')),
            ],
            options={
                'verbose_name_plural': 'Recipe categories',
            },
        ),
        migrations.CreateModel(
            name='UserRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(help_text='Please give your recipe a good name | Max Characters 75', max_length=75)),
                ('recipe_picture', models.ImageField(blank=True, default='', help_text='Please take a good picture of recipes final product and include it here', null=True, upload_to='recipe-images/')),
                ('recipe_difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], help_text='Please choose difficulty that matches your recipe the best', max_length=13)),
                ('instructions', models.TextField(help_text='Please carefully explain instructions for your recipe | Please use to enter to go down a line to between each step | Max Characters 3000', validators=[django.core.validators.MaxLengthValidator(3000)])),
                ('recipe_ingredients', models.TextField(help_text='Please include all ingredients for this recipe | Please use to enter to go down a line to between each step | Max Characters 1000', validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('required_equipment', models.TextField(help_text='Please include all equipment needed for this recipe | Please use enter to go down a line between in each piece of equipment | Max Characters 1000', validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('created_at', models.DateField(default=django.utils.timezone.now, editable=False, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('recipe_category', models.ForeignKey(help_text='Please choose category for your recipe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_share.recipecategory')),
            ],
        ),
    ]
