# Generated by Django 5.1.2 on 2025-05-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='date',
            field=models.DateField(default=12),
            preserve_default=False,
        ),
    ]
