# Generated by Django 5.1.2 on 2025-05-04 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0002_customermessage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermessage',
            name='date',
        ),
    ]
