# Generated by Django 5.1.2 on 2025-05-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0003_remove_customermessage_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerMessage',
        ),
    ]
