# Generated by Django 5.1.2 on 2025-05-04 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
