# Generated by Django 5.1.2 on 2025-05-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0006_customermessage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
