# Generated by Django 5.2 on 2025-05-04 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0008_alter_customermessage_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='recipe-images/')),
                ('difficulty', models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('Advanced', 'Advanced')], max_length=13)),
                ('instructions', models.CharField(max_length=1000)),
                ('equipment', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
