# Generated by Django 5.2 on 2025-05-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0009_userrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'beginner'), ('Intermediate', 'intermediate'), ('Advanced', 'Advanced')], max_length=13),
        ),
    ]
