# Generated by Django 5.2 on 2025-05-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0010_alter_userrecipe_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=13),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='instructions',
            field=models.TextField(max_length=1000),
        ),
    ]
