# Generated by Django 5.2 on 2025-05-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0012_alter_userrecipe_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='equipment',
            field=models.TextField(max_length=500),
        ),
    ]
