# Generated by Django 5.2 on 2025-05-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0013_alter_userrecipe_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
