# Generated by Django 5.2 on 2025-05-04 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0014_alter_customermessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='message',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='equipment',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='instructions',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
