# Generated by Django 5.2 on 2025-05-04 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0015_alter_customermessage_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='equipment',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1)]),
        ),
    ]
