# Generated by Django 5.2 on 2025-05-04 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0016_alter_userrecipe_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='message',
            field=models.TextField(help_text='Max Characters 500', validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='equipment',
            field=models.TextField(help_text='Max Characters 500 | Please make sure equipment list is easy to understand!', validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='instructions',
            field=models.TextField(help_text='Max Characters 1000 | Please make sure instructions are clear and easy to understand!', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
