# Generated by Django 5.2 on 2025-05-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0018_recipecategory_userrecipe_recipe_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name_plural': 'Recipe categories'},
        ),
        migrations.AddField(
            model_name='recipecategory',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='category-images/'),
        ),
    ]
