# Generated by Django 5.2 on 2025-05-05 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0019_alter_recipecategory_options_recipecategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecipe',
            old_name='difficulty',
            new_name='recipe_difficulty',
        ),
        migrations.RenameField(
            model_name='userrecipe',
            old_name='name',
            new_name='recipe_name',
        ),
        migrations.RenameField(
            model_name='userrecipe',
            old_name='image',
            new_name='recipe_picture',
        ),
        migrations.RemoveField(
            model_name='userrecipe',
            name='equipment',
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='required_equipment',
            field=models.TextField(default='', help_text='Max Characters 500 | Please use enter to go down a line between in each piece of equipment!', validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='instructions',
            field=models.TextField(help_text='Max Characters 1000 | Please use to enter to go down a line to between each step!', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
