# Generated by Django 5.2 on 2025-05-05 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0020_rename_difficulty_userrecipe_recipe_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='required_equipment',
            field=models.TextField(help_text='Max Characters 500 | Please use enter to go down a line between in each piece of equipment!', validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
