# Generated by Django 5.2 on 2025-05-05 17:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0021_alter_userrecipe_required_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='instructions',
            field=models.TextField(help_text='Please include that tools will be needed for this recipe | Please use to enter to go down a line to between each step | Max Characters 1000', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='recipe_category',
            field=models.ForeignKey(help_text='Please choose category for your recipe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_share.recipecategory'),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='recipe_difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], help_text='Please choose difficulty that matches your recipe the best', max_length=13),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='recipe_name',
            field=models.CharField(help_text='Please give your recipe a good name | Max Characters 100', max_length=100),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='recipe_picture',
            field=models.ImageField(blank=True, default='', help_text='Please take a good picture of recipes final product and include it here', null=True, upload_to='recipe-images/'),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='required_equipment',
            field=models.TextField(help_text='Please carefully explain instructions for your recipe | Please use enter to go down a line between in each piece of equipment | Max Characters 500', validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
