# Generated by Django 5.2 on 2025-05-05 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0022_alter_userrecipe_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='instructions',
            field=models.TextField(help_text='Please carefully explain instructions for your recipe | Please use to enter to go down a line to between each step | Max Characters 2000', validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='required_equipment',
            field=models.TextField(help_text='Please include that tools will be needed for this recipe | Please use enter to go down a line between in each piece of equipment | Max Characters 1000', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
