# Generated by Django 5.2 on 2025-05-09 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0024_userrecipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecipe',
            name='recipe_ingredients',
            field=models.TextField(default='', help_text='Please include all ingredients for this recipe | Please use to enter to go down a line to between each step | Max Characters 1000', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='required_equipment',
            field=models.TextField(help_text='Please include all equipment needed for this recipe | Please use enter to go down a line between in each piece of equipment | Max Characters 1000', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
