# Generated by Django 5.2 on 2025-05-09 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0025_userrecipe_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='recipe_ingredients',
            field=models.TextField(help_text='Please include all ingredients for this recipe | Please use to enter to go down a line to between each step | Max Characters 1000', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
