# Generated by Django 5.2 on 2025-05-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0026_alter_userrecipe_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='recipe_name',
            field=models.CharField(help_text='Please give your recipe a good name | Max Characters 75', max_length=75),
        ),
    ]
