# Generated by Django 5.2 on 2025-05-14 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share', '0027_alter_userrecipe_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='instructions',
            field=models.TextField(help_text='Please carefully explain instructions for your recipe | Please use to enter to go down a line to between each step | Max Characters 3000', validators=[django.core.validators.MaxLengthValidator(3000)]),
        ),
    ]
